networks:
  default:
    name: camagru

services:
  mailpit:
    image: axllent/mailpit:latest
    container_name: mailpit_camagru
    ports:
      - '1025:1025'
      - '8025:8025'

  frankenphp:
    build:
      context: .
      dockerfile: ./docker/services/frankenphp/Dockerfile
    container_name: frankenphp_camagru
    ports:
      - "80:80" # HTTP
      - "443:443" # HTTPS
      - "443:443/udp" # HTTP/3
    volumes:
      - ./app:/var/www/html/camagru
      - ./docker/services/frankenphp/Caddyfile:/etc/caddy/Caddyfile
      - ./docker/services/frankenphp/php.ini:/usr/local/etc/php/php.ini
    tty: true
    depends_on:
      - mysql_8
      - mailpit

  mysql_8:
    image: mysql:8.0.28
    restart: unless-stopped
    tty: true
    container_name: mysql8_camagru
    platform: "linux/x86_64"
    ports:
      - '3306:3306'
    volumes:
      # mount your MySQL 8 data directory
      - ./docker/services/mysql/8:/var/lib/mysql
      - ./docker/services/mysql/scripts/create.sh:/create.sh
    environment:
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      TZ: "Europe/Zurich"

  adminer:
    image: adminer:latest
    restart: unless-stopped
    container_name: adminer_camagru
    ports:
      - '8080:8080'
    environment:
      ADMINER_DEFAULT_SERVER: mysql_8