#!/usr/bin/env php
<?php

namespace Camagru;

// Define the base path of the application one level above the public directory
define('BASE_PATH', dirname(__DIR__) . '/app');
require_once __DIR__ . '/main.php';

// Register the autoloader...
require_once __DIR__ . '/helpers/autoloader.php';

use Camagru\core\database\Runner;
use Camagru\core\database\Database;

// Instantiate the database connection
$db = new Database();

// Track migrations if not already done
$db->trackMigration();

// Retrieve command line arguments
$args = $_SERVER['argv'];
$command = $args[1] ?? null; // The command is expected as the second argument

// Create an instance of the migration runner
$migrations = new Runner($db);

// Process the command
switch ($command) {
    case 'run':
        $migrations->run();
        break;
    case 'rollback':
        $migrations->rollback();
        break;
    case 'reset':
        $migrations->reset();
        break;
    default:
        echo "Usage: migrate.php [run|rollback|reset]\n";
        break;
}