#!/usr/bin/env php
<?php

namespace Camagru;

// Define the base path of the application one level above the public directory
define('BASE_PATH', dirname(__DIR__) . '/camagru');
require_once BASE_PATH . '/main.php';

// Register the autoloader...
require_once BASE_PATH . '/helpers/autoloader.php';

use Camagru\helpers\Config;
use Camagru\helpers\Env;
use Camagru\core\database\seeders\PageSeeders;
use Camagru\core\database\seeders\PostSeeders;
use Camagru\core\database\seeders\UserSeeders;
use Camagru\core\database\seeders\MediaSeeders;

// Load environment variables
Env::load(BASE_PATH . '/.env');

// Load the application configuration
Config::load(BASE_PATH . '/config/app.php');

// Instantiate the database connection
$seeders = [
    new UserSeeders(),
    new PageSeeders(),
    new PostSeeders(),
    new MediaSeeders(),
];

foreach ($seeders as $seeder) {
    if (method_exists($seeder, 'run')) {
        $seeder->run();
    } else {
        echo "Seeder class not found up method: " . get_class($seeder) . "\n";
    }
}