#!/usr/bin/env php
<?php

namespace Camagru;

// Define the base path of the application one level above the public directory
define('BASE_PATH', dirname(__DIR__) . '/app');
require_once __DIR__ . '/main.php';

// Register the autoloader...
require_once __DIR__ . '/helpers/autoloader.php';

use Camagru\core\database\seeders\PageSeeders;
use Camagru\core\database\seeders\PostSeeders;
use Camagru\core\database\seeders\UserSeeders;
use Camagru\core\database\seeders\LikeSeeders;
use Camagru\core\database\seeders\CommentSeeders;

// Instantiate the database connection
$seeders = [
    new PageSeeders(),
    new PostSeeders(),
    new UserSeeders(),
    new LikeSeeders(),
    new CommentSeeders(),
];

foreach ($seeders as $seeder) {
    if (method_exists($seeder, 'run')) {
        $seeder->run();
    } else {
        echo "Seeder class not found: $seeder\n";
    }
}
